const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Hollywaygloba API Documentation',
    description:
      'Hollywaygloba Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
};

const outputFile = '../swagger-output.json';
const endpointFile = ['../server.ts'];

swaggerAutogen(outputFile, endpointFile, doc).then(() => {
    require('../server.ts');        
})
